# Generated by Django 3.2.8 on 2021-11-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img_link',
            field=models.TextField(default='https://st.depositphotos.com/1741875/1237/i/600/depositphotos_12376816-stock-photo-stack-of-old-books.jpg', null=True),
        ),
    ]
