# Generated by Django 3.2.8 on 2021-11-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, default='Anomymous User', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
